### PR TITLE
Only copy extra files when extra files exist

### LINKED ISSUE #63: Thesis import fails over missing files
Thesis import should not fail over missing docx files. 

```
java.io.FileNotFoundException: /home/dspace/dspace_imports/theses/2021/economics/submission_10347/Radensky_Andre_Final_Thesis.docx (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at org.dspace.app.itemimport.ItemImport.processContentFileEntry(ItemImport.java:1552)
	at org.dspace.app.itemimport.ItemImport.processContentsFile(ItemImport.java:1477)
	at org.dspace.app.itemimport.ItemImport.addItem(ItemImport.java:876)
	at org.dspace.app.itemimport.ItemImport.addItems(ItemImport.java:736)
	at org.dspace.app.itemimport.ItemImport.main(ItemImport.java:498)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.dspace.app.launcher.ScriptLauncher.runOneCommand(ScriptLauncher.java:226)
	at org.dspace.app.launcher.ScriptLauncher.main(ScriptLauncher.java:78)
java.io.FileNotFoundException: /home/dspace/dspace_imports/theses/2021/economics/submission_10347/Radensky_Andre_Final_Thesis.docx (No such file or directory)
```

### PR DESCRIPTION
**Pull request by bess**
Fixes #63

### CODE REVIEW

File: lib/etd_transformer/transformer.rb [hunk 1]
```diff
@@ -106,6 +106,8 @@ def copy_contents_file(dataspace_submission)
     def copy_contents(vireo_submission, dataspace_submission)
       parsed = CSV.read(vireo_submission.contents_file, col_sep: "\t", quote_char: nil)
       extra_file = parsed.select { |a| a[1] == "bundle:CONTENT" }.flatten.first
+      return unless extra_file
```
Comment (jrgriffiniii) [inline lib/etd_transformer/transformer.rb:109]: 👍

File: spec/etd_transformer/transformer_spec.rb [hunk 2]
```diff
@@ -106,6 +106,12 @@
         transformer.copy_contents(vs, ds)
         expect(File.exist?(destination_path)).to eq true
       end
+      context 'when there are no extra files' do
```
Comment (jrgriffiniii) [inline spec/etd_transformer/transformer_spec.rb:109]: 👍

**Review by jrgriffiniii — APPROVED** [review]
