### PR TITLE
When there are lots of extra files, copy them all

### LINKED ISSUE #63: Thesis import fails over missing files
Thesis import should not fail over missing docx files. 

```
java.io.FileNotFoundException: /home/dspace/dspace_imports/theses/2021/economics/submission_10347/Radensky_Andre_Final_Thesis.docx (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at org.dspace.app.itemimport.ItemImport.processContentFileEntry(ItemImport.java:1552)
	at org.dspace.app.itemimport.ItemImport.processContentsFile(ItemImport.java:1477)
	at org.dspace.app.itemimport.ItemImport.addItem(ItemImport.java:876)
	at org.dspace.app.itemimport.ItemImport.addItems(ItemImport.java:736)
	at org.dspace.app.itemimport.ItemImport.main(ItemImport.java:498)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.dspace.app.launcher.ScriptLauncher.runOneCommand(ScriptLauncher.java:226)
	at org.dspace.app.launcher.ScriptLauncher.main(ScriptLauncher.java:78)
java.io.FileNotFoundException: /home/dspace/dspace_imports/theses/2021/economics/submission_10347/Radensky_Andre_Final_Thesis.docx (No such file or directory)
```

### PR DESCRIPTION
**Pull request by bess**
Fixes #63

### CODE REVIEW

File: lib/etd_transformer/transformer.rb [hunk 1]
```diff
@@ -99,18 +99,30 @@ def copy_contents_file(dataspace_submission)
...
 
+    ##
+    # Given a DSpace contents file, return an array of all bundle:CONTENT filenames
+    # @return [<String>] An array of all bundle:CONTENT filenames
+    def list_extra_files(contents_file)
+      parsed = CSV.read(contents_file, col_sep: "\t", quote_char: nil)
+      extra_file_pairs = parsed.select { |a| a[1] == "bundle:CONTENT" }
+      return [] unless extra_file_pairs
+
+      extra_file_pairs.map(&:first)
```
Comment (jrgriffiniii) [inline lib/etd_transformer/transformer.rb:110]: 👍

File: lib/etd_transformer/transformer.rb [hunk 2]
```diff
@@ -99,18 +99,30 @@ def copy_contents_file(dataspace_submission)
...
-      parsed = CSV.read(vireo_submission.contents_file, col_sep: "\t", quote_char: nil)
-      extra_file = parsed.select { |a| a[1] == "bundle:CONTENT" }.flatten.first
-      return unless extra_file
+      extra_files = list_extra_files(vireo_submission.contents_file)
+      return if extra_files.empty?
 
-      original = File.join(vireo_submission.source_files_directory, extra_file)
-      destination_path = File.join(dataspace_submission.directory_path, extra_file)
-      FileUtils.cp(original, destination_path)
+      extra_files.each do |filename|
```
Comment (jrgriffiniii) [inline lib/etd_transformer/transformer.rb:121]: 👍

**Review by jrgriffiniii — APPROVED** [review]
